"""Add hospital image_url

Revision ID: 38c0c61c18f2
Revises: 
Create Date: 2025-06-29 13:03:46.326702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c0c61c18f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
